---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-security
  namespace: k8s-security
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-usergroup
  namespace: k8s-security
  labels:
    name: k8s-standard
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-usergroup
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: k8s-usergroup
    spec:
      serviceAccountName: k8s-security
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 101
        fsGroup: 101
      containers:
      - image: nginxinc/nginx-unprivileged:mainline-alpine
        name: k8s-standard
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
