---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-security
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-standard
  namespace: k8s-security
  labels:
    name: k8s-standard
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-standard
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: k8s-standard
    spec:
      containers:
      - image: nginx:mainline
        name: k8s-standard
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
